        # if self.algorithm == 1:
        #     self.path = self.dijkstra_search(start_node, end_node)
        # elif self.algorithm == 2:
        #     self.path = self.a_star_search(start_node, end_node)
        # elif self.algorithm == 3:
        #     self.path = self.bfs_search(start_node, end_node)  
        # elif self.algorithm == 4:
        #     self.path = self.bestfs_search(start_node, end_node)  
        # elif self.algorithm == 5:
        #     self.path = self.dfs_search(start_node, end_node) 
